### ISSUE TITLE
Convert Windows to UNIX path without executing wslpath inside WSL distro

### ISSUE THREAD

**Issue by nscuro** [nscuro/bradamsa-ng#4]

**Comment by Matt-Watkins** [comment]
Found that wslpath only succeeds when using "\\" in the native path. 
Ex. "wslpath -a -u C:\\Users\\<user>\\Documents\\intruder-input"
But the "\\" seems to get stripped out when passed to wslpath, resulting in an error and exit code 2. 
Great work btw.

**Comment by nscuro** [comment]
Thanks for your input @Matt-Watkins. As this issue suggests I'm in the process of moving away from `wslpath` because it can only be executed from within a WSL distro, which is kinda inconvenient. 

I'll make sure to properly handle all kinds of separators when implementing this. Let me know if you find more issues.

**Comment by nscuro** [comment]
Should be fixed as of #6. The Windows -> UNIX path conversion is now performed manually without executing `wslpath`. Also the Windows / input Path now isn't user-provided anymore.
